// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace PuppyMP_SB
{
	public partial class btnSyllableDeletion : UIButton
	{
		public btnSyllableDeletion (IntPtr handle) : base (handle)
		{
		}
	}
}
