// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SharedPCL;

namespace speechTherapy
{
	public partial class PositionViewController : UIViewController
	{

		List<Pair> pairList { get; set; }
		public speechTherapyViewController Delegate { get; set; }
		private List<Pair> initialList = new List<Pair>();
		private List<Pair> finalList = new List<Pair>();

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			splitLists ();


		}

		public PositionViewController (IntPtr handle) : base (handle)
		{

		}


	
		//function to be called by preparesegue when being called.
		public void setPairList(speechTherapyViewController vc, List<Pair> inputPairList)
		{
			Delegate = vc;
			pairList = inputPairList;
		}

		private void splitLists ()
		{
			foreach (Pair pair in pairList) 
			{
				switch (pair.position) {
				case "Initial":
					initialList.Add (pair);
					break;
				case "Final":
					finalList.Add (pair);
					break;
				default:
					break;
				}
			}
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			var ImageVC = segue.DestinationViewController as imagePgViewController;

			if (segue.Identifier == "initial_position") {

				ImageVC.setPairList (this, initialList);

			} else if (segue.Identifier == "final_position") {

				ImageVC.setPairList (this, finalList);
			}
		}
	}
}
