// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SharedPCL;

namespace speechTherapy
{
	public partial class secondView : UIViewController
	{
		public secondView (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			secondOutlet.Text = "Yup";


			// Perform any additional setup after loading the view, typically from a nib.
		}
	}
}
